[package]
name = "lightcycles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip=true
lto=true
panic="abort"

[dependencies]
fastrand="1.9.0"
termion="2.0.1"
